parameters:
    wondercache.data_collector.template: "LioshiWonderCacheBundle:Collector:wondercache"


services:
    wonder.cache.invalidator:
        class: Lioshi\WonderCacheBundle\Cache\CacheInvalidator
        public: false
        tags:
            - { name: doctrine.event_listener, event: onFlush }
        arguments: [ @service_container ]

    wonder.cache:
        class: Lioshi\WonderCacheBundle\Cache\WonderCache
        arguments: ['@service_container']
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
            - { name: kernel.event_listener, event: kernel.terminate, method: onKernelResponse }

    wonder.cache.logger:
        class: Lioshi\WonderCacheBundle\Logger\WonderCacheLogger

    wonder.cache.data_collector:
        class: Lioshi\WonderCacheBundle\DataCollector\WonderCacheDataCollector
        arguments: [@wonder.cache.logger]
        tags: 
            - { name: data_collector, template: %wondercache.data_collector.template%, id: "wondercache" }
