services:
    wonder.cache.invalidator:
        class: Lioshi\WonderCacheBundle\Cache\CacheInvalidator
        public: false
        tags:
            - { name: doctrine.event_listener, event: onFlush }
        arguments: [ @service_container ]

    wonder.cache:
        class: Lioshi\WonderCacheBundle\Cache\WonderCache
        arguments: ['@service_container']
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
            - { name: kernel.event_listener, event: kernel.terminate, method: onKernelResponse }



